### PR TITLE
Licensing param types

### PR DESCRIPTION
**Pull request by DanRathbun**
Issue #5 Sketchup::Licensing - fix tutorial link

Issue #12 Sketchup::Licensing cleanup
a. First introductory sentence: code object emphasis (+ delimiters) for `Sketchup::Licensing`
b. Add blank line after introductory sentence & reformat 2nd paragraph.
c. In `get_extension_license` method:
  1. param type needs `[]` delimiters for class linking.
  2. return type needs `[]` delimiters for class linking.
  3. Capitalize 1st description sentence of `@return`.

### CODE REVIEW

**Comment by thomthom** [comment]
Thanks.

I tried to merge this but my tool threw an error - not sure why. Need to poke into this tomorrow.

**Comment by DanRathbun** [comment]
Probably needs to be done AFTER the FrameChangeObser merge. (I had made a booboo, and not created branches, so both of these issues were appended onto one another "from master".
So I reverted, created separate branches, and re-requested each Pull from it's own branch. But the reverting had to be done first, which was part of the FrameChangeObserver PR.
Try again.

**Comment by thomthom** [comment]
The FrameChangeObserver when fine. I saw that was a few commits in the history of that, but it worked fine on my end.  I think it's my change-parser that is running into an unexpected condition.

**Comment by DanRathbun** [comment]
I used a RDoc style link syntax for the tutorial link. 

Perhaps your tool expects YARD style so it can import back into RDoc style in the C++ ?

**Comment by thomthom** [comment]
YARD can use different syntax - the default is RDoc, which we stuck with because existing docs was close to that. So it's all RDoc with YARD tags - so it should be fine. I can suspecting it's related to my script that analyse the git diffs.

**Comment by DanRathbun** [comment]
**What is with this conflict ?**

This PR should have had only one file, ie: `"SketchUp/Sketchup/Licensingr.rb"`

**Comment by thomthom** [comment]
Yea, I noticed that conflict myself yesterday. Not sure what that was.

Sorry for the delay in merging this - there has been so much going lately that I've not had any time to dig into what is causing the merge tool to fail on my end. I hope I'll get to it next week.

**Comment by DanRathbun** [comment]
Um, .. this PR is still open.

 And why was "master" merged into THIS branch, instead of the reverse ?

**Comment by thomthom** [comment]
Master the the branch where I have been generating the stubs. For the previous PRs I merged them into a development branch in hopes that could allow GitHub to show credit. 

However, the generated stubs is the ruling source here - so I'm merging master into the development branch in order to keep the development branch in sync.

If I were to merge these PRs into master I'd run into conflicts when I run the generator.

**Comment by DanRathbun** [comment]
Okay I'm totally confused as to what I need to sync my local repo with, ie what do I need to stay in sync with ?.

**Comment by thomthom** [comment]
Sync with `master`.

**Pull request merged**
